In [1]:
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[-2.2942e-30,  8.6040e-43, -2.2942e-30],
        [ 8.6040e-43, -2.2939e-30,  8.6040e-43],
        [-2.2939e-30,  8.6040e-43, -2.2940e-30],
        [ 8.6040e-43, -2.2940e-30,  8.6040e-43],
        [-2.2937e-30,  8.6040e-43, -2.2937e-30]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2068, 0.1128, 0.9917],
        [0.8318, 0.1007, 0.7909],
        [0.8597, 0.7187, 0.2876],
        [0.4358, 0.8365, 0.9973],
        [0.5062, 0.9662, 0.6257]])


In [7]:
x = torch.ones(5, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [8]:
print(x.size())

torch.Size([5, 3])
